### ISSUE TITLE
Console commands for managing the admin account

### ISSUE THREAD

**Issue by pxgamer** [pxgamer/cachent#15]
Currently the admin account is created by a seeder.

In production, seeders should not be used, so it may be better to add some commands such as:
- `artisan cachent:admin --generate`
- `artisan cachent:admin --username {{ username }}`
- `artisan cachent:admin --password {{ password }}`
- `artisan cachent:admin --email {{ email }}`

**Comment by hi15** [comment]
I will work on it!

**Comment by pxgamer** [comment]
@hi15 Cheers. 👍

**Comment by pxgamer** [comment]
Added in #18.
