### ISSUE TITLE
Add name listing for torrent files

### ISSUE THREAD

**Issue by pxgamer** [pxgamer/cachent#7]
When viewing the stats page for a torrent, it could show the internal name of the file, as well as the hash.

**Comment by aekazitt** [comment]
Hi, let me take a stab at this if I could. Not used to PHP though

**Comment by pxgamer** [comment]
@aekazitt of course 👍 No problem.

**Comment by aekazitt** [comment]
@pxgamer Any problems?

**Comment by pxgamer** [comment]
I think I should have been more clear, this is actually for the torrent's name (internal) rather than the file's name. :+1: Sorry.

**Comment by pxgamer** [comment]
This was implemented in #11 and ff24c891a2ac46c5927e4695f4b1e918ee374dc7.
